# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(884, 816)
    self.driver.find_element(By.LINK_TEXT, "Sign up here").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Praveena")
    self.driver.find_element(By.NAME, "lname").send_keys("R")
    self.driver.find_element(By.NAME, "new-email").send_keys("praveena@gmail.com")
    self.driver.find_element(By.NAME, "new-username").send_keys("praveena")
    self.driver.find_element(By.NAME, "new-password").send_keys("123")
    self.driver.find_element(By.NAME, "new-password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "username").click()
  
