# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdopt():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adopt(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(878, 816)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("priyankaa")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("pri")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Pets Corner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pets-section:nth-child(1) .pet-data:nth-child(3) > .adopt-btn").click()
    self.driver.find_element(By.ID, "first-name").click()
    self.driver.find_element(By.ID, "first-name").send_keys("Priyanka")
    self.driver.find_element(By.ID, "last-name").send_keys("Anand")
    self.driver.find_element(By.ID, "address").send_keys("47")
    self.driver.find_element(By.ID, "city-state").send_keys("Karnataka")
    self.driver.find_element(By.ID, "zipcode").send_keys("560043")
    self.driver.find_element(By.ID, "phone").send_keys("6360223782")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("priyanka.whee@gmail.com")
    self.driver.find_element(By.ID, "adopter-form").click()
    self.driver.find_element(By.ID, "home-type").click()
    self.driver.find_element(By.ID, "home-type").send_keys("House")
    self.driver.find_element(By.ID, "reason").send_keys("Companion")
    self.driver.find_element(By.ID, "current-pets").click()
    self.driver.find_element(By.ID, "current-pets").send_keys("Don\'t have any")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
